// <auto-generated />
using System;
using CourseForge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourseForge.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260211180000_InitialCreate")]
public partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("CourseForge.Api.Models.Course", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<int>("InstructorId")
                    .HasColumnType("integer");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("character varying(120)");

                b.HasKey("Id");

                b.HasIndex("InstructorId");

                b.ToTable("Courses");
            });

        modelBuilder.Entity("CourseForge.Api.Models.Enrollment", b =>
            {
                b.Property<int>("UserId")
                    .HasColumnType("integer");

                b.Property<int>("CourseId")
                    .HasColumnType("integer");

                b.HasKey("UserId", "CourseId");

                b.HasIndex("CourseId");

                b.ToTable("Enrollments");
            });

        modelBuilder.Entity("CourseForge.Api.Models.InstructorProfile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Bio")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<int>("UserId")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("UserId")
                    .IsUnique();

                b.ToTable("InstructorProfiles");
            });

        modelBuilder.Entity("CourseForge.Api.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("character varying(120)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("Users");
            });

        modelBuilder.Entity("CourseForge.Api.Models.Course", b =>
            {
                b.HasOne("CourseForge.Api.Models.User", "Instructor")
                    .WithMany("CoursesTeaching")
                    .HasForeignKey("InstructorId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Instructor");
            });

        modelBuilder.Entity("CourseForge.Api.Models.Enrollment", b =>
            {
                b.HasOne("CourseForge.Api.Models.Course", "Course")
                    .WithMany("Enrollments")
                    .HasForeignKey("CourseId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CourseForge.Api.Models.User", "User")
                    .WithMany("Enrollments")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Course");

                b.Navigation("User");
            });

        modelBuilder.Entity("CourseForge.Api.Models.InstructorProfile", b =>
            {
                b.HasOne("CourseForge.Api.Models.User", "User")
                    .WithOne("InstructorProfile")
                    .HasForeignKey("CourseForge.Api.Models.InstructorProfile", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("CourseForge.Api.Models.User", b =>
            {
                b.Navigation("CoursesTeaching");

                b.Navigation("Enrollments");

                b.Navigation("InstructorProfile");
            });
#pragma warning restore 612, 618
    }
}
